apiVersion: apps/v1
kind: Deployment
metadata:
  name: reddit-clone-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: reddit-clone-app:1.0.0-27
  template:
    metadata:
      labels: 
        app: reddit-clone-app:1.0.0-27
    spec:
      containers:
        - name: reddit-clone-app:1.0.0-27
          image: shubham1166/reddit-clone-pipeline:1.0.0-27
          resources:
            limits:
              cpu: "1"
            requests:
              cpu: "500m"
          ports:
            - containerPort: 3000
      
       


